image: docker.slock.it/build-images/node:10-alpine

stages:
  - deploy

push-to-github:
  stage: deploy
  variables:
    GITHUB_REPO_NAME: ew-market-matcher
    GIT_STRATEGY: clone
  only:
    - '/^v\d+\.\d+\.\d+\-release$/'
  tags:
    - short-jobs
  script:
    - CLEAN_VERSION=`echo "$CI_COMMIT_TAG"|sed s/-release//`
    - echo "using $CLEAN_VERSION as version"
    - echo -e "$CI_SSH_KEY" > /gitkey
    - chmod 0400 /gitkey
    - export GIT_SSH_COMMAND="/usr/bin/ssh -o StrictHostKeyChecking=no -i /gitkey"
    - git remote add external git@github.com:energywebfoundation/${GITHUB_REPO_NAME}.git
    - git push --force external HEAD:refs/heads/master
    - git tag | grep -v '\-release' | xargs git tag --delete 
    - git tag $CLEAN_VERSION
    - git push --force external --tag $CLEAN_VERSION
    - rm /gitkey
